### ISSUE TITLE
Add supplemented Gene Validity Proband Evidence fields to UI

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph-ui#13]
Genegraph has supplemented the following proband fields to Proband Evidence that need to be added to the UI:
ageType
ageUnit
ageValue
alleleOrigin
ethnicity
phenotypes
phenotypeFreeTest
previousTesting
previousTestingDescription
scoreStatus
sex
tetsingMethods
variantType

**Comment by larrybabb** [comment]
@toneillbroad please remind me what these tickets mean in terms of being in "review". If you are using this for your own purposes and no one else on the team is involved in "checking the work" then please re-clarify that. I'm trying to see if we can get the items in review to be prioritized and expedited so we can get them closed quickly.

**Comment by toneillbroad** [comment]
Tickets in review have not been verified by Phil or may not have been documented yet.
